// modes-audit — EVERY module under the editor's two modes and Play (roadmap 30, lane
// 30-mod-audit). Core 30 P1-P4 split the editor click into EDIT (a click selects; a module
// click handler runs only if it asked for {modes: ['edit']}) and INTERACT (the play-style
// click), and listed scene-root module content in the object list's "Module content"
// section. This flight measures, per module, what a USER meets:
//
//   list      every object/row the module made appears in the object list — the scene
//             tree for objectsGroup content, the Module content section (with a label a
//             person reads) for scene-root groups
//   select    a REAL click on its projected pixel in EDIT selects it (or its proxy)
//   move      a real gizmo drag moves a replicated object; scene-root content is
//             regenerated by its module, so there it asserts READ-ONLY instead (the proxy
//             is selected, no gizmo, nothing joins the selection set)
//   editQuiet the same EDIT click on the module's interactive part does NOT interact
//   interact  in INTERACT a real click on it does the module's thing (a key sounds, a
//             button presses) and selects nothing
//   play      in PLAY (isLocked, the crosshair tap — play-interact's recipe) it still does
//
// Content is created the way a user does: the module's menu button, its /create
// primitive, its toolbox, or its Games-tab template (read from the scenes checkout,
// SCENES_DIR, never written). Every viewport click lands on a pixel verified FIRST to
// resolve to the intended mesh through the app's own pick, so no cell can pass on a
// click that hit empty space. A cell that cannot apply is N-A with its reason.
//
//   APP_URL=… node tests/modes-audit.test.cjs            every module
//   ONLY=piano,music-lab node tests/modes-audit.test.cjs  a few
//   AUDIT_OUT=/path/report.json                           also write the table as JSON
const h = require('./helpers.cjs');
const fs = require('fs');
const path = require('path');

const SCENES_DIR = process.env.SCENES_DIR || path.resolve(__dirname, '../../scenes');
const ONLY = (process.env.ONLY || '').split(',').filter(Boolean);
const VIEW = { width: 1540, height: 774 };
const COLUMNS = ['list', 'select', 'move', 'editQuiet', 'interact', 'play'];

// ---------------------------------------------------------------------------------
// in-page toolkit, installed once per page as window.__audit
// ---------------------------------------------------------------------------------
function pageLib() {
	const s = window.__stores;
	// NOT 0: core's flyTo divides by its duration, and a 0 ms tween leaves the camera at NaN
	// for a frame (measured: the door-keypad row's listener threw "non-finite AudioParam")
	const FLY_MS = 1;
	const THREE = s.THREE;
	const read = (name) => {
		let v;
		s[name].subscribe((x) => (v = x))();
		return v;
	};
	const objects = () => read('objectsGroup');
	const scene = () => read('globalScene');
	const camera = () => read('globalCamera');
	const canvas = () => read('globalRenderer').domElement;
	const topOf = (node) => {
		const root = objects();
		while (node && node.parent && node.parent !== root) node = node.parent;
		return node?.parent === root ? node : null;
	};
	/** the root a spec names: an objectsGroup uuid, or a scene-root group */
	const rootOf = (spec) =>
		spec.uuid ? objects().getObjectByProperty('uuid', spec.uuid) : spec.group ? scene().getObjectByName(spec.group) : null;
	/** does `mesh` satisfy the spec's part filter? */
	const partOk = (spec, mesh) => {
		if (!mesh) return false;
		if (spec.part) {
			const re = new RegExp(spec.part);
			for (let n = mesh; n; n = n.parent) {
				if (re.test(n.name ?? '')) return true;
				if (n === rootOf(spec)) break;
			}
			return false;
		}
		if (spec.midi != null) return mesh.userData?.midi === spec.midi;
		if (spec.anyMidi) return typeof mesh.userData?.midi === 'number';
		if (spec.userKey) return !!mesh.userData?.[spec.userKey] || !!mesh.parent?.userData?.[spec.userKey];
		return true;
	};
	/** the mesh to aim at: the first visible mesh under the root that satisfies the spec */
	const meshOf = (spec) => {
		const root = rootOf(spec);
		if (!root) return null;
		let found = null;
		root.traverseVisible?.((n) => {
			if (!found && n.isMesh && !n.userData?.isModuleProxy && partOk(spec, n)) found = n;
		});
		return found;
	};
	/** does a hit mesh belong to what the spec aims at? */
	const hitOk = (spec, mesh) => {
		const root = rootOf(spec);
		if (!root || !mesh) return false;
		let inside = false;
		for (let n = mesh; n; n = n.parent) if (n === root) inside = true;
		return inside && partOk(spec, mesh);
	};
	/** every hit the EDITOR pick would consider, nearest first: module groups + the scene */
	// (`extra` = the spec's own scene-root group, so the PIXEL check asks "is this content
	// the nearest thing here" even where the app does not pick it — the click then says
	// what the app does with it)
	const allHits = (ray, extra = null) => {
		const hits = [...s.scenePick.sceneHits(ray, { tinyProxies: true })];
		const names = new Set(s.moduleSDK.moduleInteractiveGroups);
		if (extra) names.add(extra);
		for (const name of names) {
			const root = scene().getObjectByName(name);
			if (root) hits.push(...ray.intersectObject(root, true));
		}
		return hits.filter((hit) => hit.object?.visible !== false).sort((a, b) => a.distance - b.distance);
	};
	/** the hit the editor pick PREFERS: core 30 P2's select-through skips a see-through
	 * shell (effective opacity < 0.25, `userData.pick === 'through'`, a hidden node) in
	 * front of an opaque target, so the pixel check must too */
	const seeThrough = (object) => {
		for (let n = object; n; n = n.parent) {
			if (n.visible === false || n.userData?.pick === 'through') return true;
			if (n === objects() || n === scene()) break;
		}
		const m = Array.isArray(object.material) ? object.material[0] : object.material;
		return !!m && m.transparent && (m.opacity ?? 1) < 0.25;
	};
	const firstHit = (ray, extra) => {
		const hits = allHits(ray, extra);
		return hits.find((hit) => !seeThrough(hit.object)) ?? hits[0] ?? null;
	};
	/** fly the editor camera so the spec's mesh fills a good part of the view */
	const frame = (spec, opts = {}) => {
		const mesh = meshOf(spec);
		if (!mesh) return false;
		mesh.updateWorldMatrix(true, true);
		const box = new THREE.Box3().setFromObject(mesh);
		const centre = box.getCenter(new THREE.Vector3());
		const size = box.getSize(new THREE.Vector3()).length();
		const dist = opts.dist ?? Math.min(4.5, Math.max(1.2, size * 2.2));
		const dir = new THREE.Vector3(...(opts.from ?? [0, 0.9, 1.4])).normalize();
		const at = centre.clone().addScaledVector(dir, dist);
		// `shift` slides the view sideways (fractions of the distance) so the mesh lands
		// off-centre — past a game's HUD card, which sits over the middle in the editor
		const [sx, sy] = opts.shift ?? [0, 0];
		const right = new THREE.Vector3().crossVectors(new THREE.Vector3(0, 1, 0), dir).normalize();
		const up = new THREE.Vector3().crossVectors(dir, right).normalize();
		const slide = right.multiplyScalar(sx * dist).add(up.multiplyScalar(sy * dist));
		s.objectActions.flyTo(at.add(slide).toArray(), centre.clone().add(slide).toArray(), FLY_MS);
		return true;
	};
	/** a pixel over the spec's mesh whose FIRST editor hit is that mesh, on the canvas */
	const aim = (spec) => {
		const mesh = meshOf(spec);
		if (!mesh) return { ok: false, why: 'no mesh' };
		mesh.updateWorldMatrix(true, true);
		const box = new THREE.Box3().setFromObject(mesh);
		const rect = canvas().getBoundingClientRect();
		const cam = camera();
		const ray = new THREE.Raycaster();
		ray.layers.enableAll();
		const candidates = [];
		const c = box.getCenter(new THREE.Vector3());
		candidates.push(c.clone(), new THREE.Vector3(c.x, box.max.y - 0.002, c.z));
		for (const fx of [0.3, 0.5, 0.7])
			for (const fz of [0.3, 0.5, 0.7])
				candidates.push(new THREE.Vector3(box.min.x + (box.max.x - box.min.x) * fx, box.max.y - 0.002, box.min.z + (box.max.z - box.min.z) * fz));
		for (const fy of [0.3, 0.6]) candidates.push(new THREE.Vector3(c.x, box.min.y + (box.max.y - box.min.y) * fy, box.max.z - 0.002));
		let last = null;
		for (const p of candidates) {
			const v = p.clone().project(cam);
			if (Math.abs(v.x) > 0.95 || Math.abs(v.y) > 0.95 || v.z > 1) continue;
			const x = rect.left + ((v.x + 1) / 2) * rect.width;
			const y = rect.top + ((1 - v.y) / 2) * rect.height;
			if (document.elementFromPoint(x, y) !== canvas()) {
				last = 'covered by ' + (document.elementFromPoint(x, y)?.id || document.elementFromPoint(x, y)?.className || '?');
				continue;
			}
			ray.setFromCamera(new THREE.Vector2(v.x, v.y), cam);
			const first = firstHit(ray, spec.group);
			if (first && hitOk(spec, first.object)) return { ok: true, x, y, first: first.object.name || first.object.type };
			last = 'first hit ' + (first ? first.object.name || first.object.type : 'nothing');
		}
		return { ok: false, why: last ?? 'off screen' };
	};
	/** is the spec's mesh the first thing under the CROSSHAIR (play's aim), within reach? */
	const centreAim = (spec) => {
		const ray = new THREE.Raycaster();
		ray.setFromCamera(new THREE.Vector2(0, 0), camera());
		const first = firstHit(ray, spec.group);
		return { ok: !!first && hitOk(spec, first.object) && first.distance <= 6, first: first?.object?.name ?? null, distance: first?.distance ?? null };
	};
	/** frame the mesh dead centre (play aims through the view's centre) */
	const frameCentre = (spec, dist = 1.6) => {
		const mesh = meshOf(spec);
		if (!mesh) return false;
		const box = new THREE.Box3().setFromObject(mesh);
		const centre = box.getCenter(new THREE.Vector3());
		if (spec.top) centre.y = box.max.y - 0.01;
		const dir = new THREE.Vector3(0, 1.1, 1).normalize();
		s.objectActions.flyTo(centre.clone().addScaledVector(dir, dist).toArray(), centre.toArray(), FLY_MS);
		return true;
	};
	/** PLAY aims through the view's centre from the camera play hands it, which the editor
	 * cannot fly (the orbit controls stand down in play) — so, like play-interact, move the
	 * TARGET: its root shifts until the spec's mesh sits `dist` down the crosshair */
	const placeCentre = (spec, dist = 1.6) => {
		const mesh = meshOf(spec);
		const root = rootOf(spec);
		if (!mesh || !root) return false;
		const cam = camera();
		const want = cam.getWorldPosition(new THREE.Vector3()).addScaledVector(cam.getWorldDirection(new THREE.Vector3()), dist);
		const have = new THREE.Box3().setFromObject(mesh).getCenter(new THREE.Vector3());
		const delta = want.sub(have);
		const local = root.parent.worldToLocal(root.getWorldPosition(new THREE.Vector3()).add(delta));
		root.position.copy(local);
		root.updateMatrixWorld(true);
		if (spec.uuid) s.objectsGroup.update((v) => v);
		return true;
	};
	/** ...or move the PLAYER: the rig (the play camera's parent) steps so the camera sits
	 * `dist` back from the mesh along its own view. The target stays put — an object an
	 * effect node pins (a collectible, a football button) is re-seated every frame. */
	const aimRig = (spec, dist = 1.6) => {
		const mesh = meshOf(spec);
		const cam = camera();
		const rig = cam?.parent;
		if (!mesh || !rig || rig === scene()) return false;
		const centre = new THREE.Box3().setFromObject(mesh).getCenter(new THREE.Vector3());
		const want = centre.addScaledVector(cam.getWorldDirection(new THREE.Vector3()), -dist);
		const delta = want.sub(cam.getWorldPosition(new THREE.Vector3()));
		const next = rig.getWorldPosition(new THREE.Vector3()).add(delta);
		rig.position.copy(rig.parent ? rig.parent.worldToLocal(next) : next);
		rig.updateMatrixWorld(true);
		return true;
	};
	const selection = () => read('selectedObjects');
	const playDebug = () => s.playInteract.playInteractDebug?.() ?? null;
	const moduleSelection = () => s.moduleSDK.moduleContentDebug?.().selection?.name ?? null;
	const gizmoObject = () => read('TControls')?.object?.uuid ?? null;
	/** the translate gizmo's X picker, as a screen segment to drag along */
	const gizmoHandle = (axis = 'X') => {
		const controls = read('TControls');
		const helper = controls?.getHelper?.() ?? controls;
		if (!helper) return null;
		let gizmo = null;
		helper.traverse((n) => {
			if (!gizmo && n.picker?.translate) gizmo = n;
		});
		const pickX = gizmo?.picker?.translate?.children?.find((n) => n.name === axis);
		if (!pickX) return null;
		pickX.updateWorldMatrix(true, false);
		const box = new THREE.Box3().setFromObject(pickX);
		const mid = box.getCenter(new THREE.Vector3());
		const origin = controls.object.getWorldPosition(new THREE.Vector3());
		const rect = canvas().getBoundingClientRect();
		const px = (p) => {
			const v = p.clone().project(camera());
			return [rect.left + ((v.x + 1) / 2) * rect.width, rect.top + ((1 - v.y) / 2) * rect.height];
		};
		const a = px(origin);
		const b = px(mid);
		const len = Math.hypot(b[0] - a[0], b[1] - a[1]) || 1;
		return { x: b[0], y: b[1], dx: (b[0] - a[0]) / len, dy: (b[1] - a[1]) / len, onCanvas: document.elementFromPoint(b[0], b[1]) === canvas() };
	};
	const position = (uuid) => objects().getObjectByProperty('uuid', uuid)?.position.toArray() ?? null;
	/** a module reacted: its sends, the replicated notes/params, flow pulses, toasts */
	const reaction = () => {
		const triggers = read('flowTriggers') ?? {};
		let pulses = 0;
		for (const entry of Object.values(triggers)) pulses += (entry?.lastT ?? 0) + (entry?.count ?? 0);
		return {
			sent: (window.__auditSent ?? []).filter((m) => !/look|cursor|presence|ping|heartbeat|camera|clock|avatar|pose|lock|select|^move|nodesync/i.test(m.type + ':' + (m.op ?? ''))).length,
			pulses,
			toasts: (read('toastStore') ?? []).length
		};
	};
	return {
		read,
		objects,
		scene,
		topOf,
		rootOf,
		meshOf,
		frame,
		aim,
		centreAim,
		frameCentre,
		placeCentre,
		aimRig,
		selection,
		playDebug,
		moduleSelection,
		gizmoObject,
		gizmoHandle,
		position,
		reaction
	};
}

async function installLib(page) {
	await page.evaluate(`window.__audit = (${pageLib.toString()})();`);
	// what left this machine: the peer's own send, wrapped (editor-modes' spy)
	await page.evaluate(() => {
		let p;
		window.__stores.peers.subscribe((v) => (p = v))();
		window.__auditSent = [];
		if (!p || p.__auditSpied) return;
		const real = p.send.bind(p);
		p.send = (msg) => {
			window.__auditSent.push({ type: msg?.type, op: msg?.op, moduleId: msg?.moduleId });
			return real(msg);
		};
		p.__auditSpied = true;
	});
}
const A = (page, fn, arg) => page.evaluate(fn, arg);
const lib = (page, call, ...args) => page.evaluate(({ call, args }) => window.__audit[call](...args), { call, args });

async function menu(page, label) {
	const ok = await page.evaluate((label) => {
		let list;
		window.__stores.moduleSDK.moduleMenuItems.subscribe((v) => (list = v))();
		const item = list.find((m) => m.label === label);
		if (!item) return false;
		item.action();
		return true;
	}, label);
	if (!ok) throw new Error('no module menu item "' + label + '"');
}
async function create(page, command) {
	await page.evaluate((c) => window.__stores.commandsHandler.sceneCommand(c), command);
	await page.waitForTimeout(400);
	return page.evaluate(() => {
		let g;
		window.__stores.objectsGroup.subscribe((v) => (g = v))();
		return g.children[g.children.length - 1]?.uuid ?? null;
	});
}
/** place a replicated object (the core suites' write: position + objectsGroup.update) */
function place(page, uuid, pos) {
	return page.evaluate(
		({ uuid, pos }) => {
			let g;
			window.__stores.objectsGroup.subscribe((v) => (g = v))();
			const o = g.getObjectByProperty('uuid', uuid);
			o.position.set(pos[0], pos[1], pos[2]);
			o.updateMatrixWorld(true);
			window.__stores.objectsGroup.update((v) => v);
		},
		{ uuid, pos }
	);
}
async function waitFor(page, fn, arg, timeout = 15000) {
	const start = Date.now();
	let last;
	while (Date.now() - start < timeout) {
		last = await page.evaluate(fn, arg);
		if (last) return last;
		await page.waitForTimeout(300);
	}
	return last;
}
/** uuids of the top-level objects of the module's audio devices, by kind prefix */
function devicesOf(page, prefix) {
	return page.evaluate((prefix) => {
		const out = [];
		for (const d of window.__stores.audioDevices.devicesDebug().built)
			if (d.kind.startsWith(prefix)) {
				let g;
				window.__stores.objectsGroup.subscribe((v) => (g = v))();
				const o = g.getObjectByProperty('uuid', d.uuid);
				if (o && o.parent === g) out.push({ uuid: d.uuid, label: d.kind.slice(prefix.length) });
			}
		return out;
	}, prefix);
}
async function loadTemplate(page, slug) {
	const file = path.join(SCENES_DIR, 'games', slug, 'scene.tpscene');
	if (!fs.existsSync(file)) throw new Error('template not found: ' + file);
	const bytes = fs.readFileSync(file);
	await page.evaluate(async (arr) => {
		const s = window.__stores;
		await s.sessions.applySession(await s.sessions.readSessionZip(new Uint8Array(arr).buffer), { backup: false });
	}, Array.from(bytes));
	await page.waitForTimeout(2500);
}
const byName = (page, name) =>
	page.evaluate((n) => {
		let g;
		window.__stores.objectsGroup.subscribe((v) => (g = v))();
		return g.children.find((c) => c.name === n)?.uuid ?? null;
	}, name);

// ---------------------------------------------------------------------------------
// the modules: how a user makes the content, what to aim at, what "it worked" reads
// ---------------------------------------------------------------------------------
// items:    [{label, uuid} | {label, group, aim?}]   — the content to list/select/move
// interact: {target, effect?, changed?}              — the interactive part + its read
// play:     same shape, or {na}
// Each `effect` defaults to window.__audit.reaction (sends, flow pulses, toasts).
const sentOp = (op) => (page) => page.evaluate((op) => (window.__auditSent ?? []).filter((m) => m.op === op).length, op);
const sentType = (type) => (page) => page.evaluate((t) => (window.__auditSent ?? []).filter((m) => m.type === t).length, type);
const noClick = (why) => ({ interact: { na: why }, play: { na: why }, editQuiet: { na: why } });

const MODULES = [
	{
		id: 'piano',
		async make(page) {
			await menu(page, 'Piano: spawn / remove');
			await waitFor(page, () => !!window.__audit.scene().getObjectByName('piano-module'));
			const piano = { group: 'piano-module', anyMidi: true };
			return {
				items: [{ label: 'the keyboard', ...piano, listLabel: 'Piano (module)', children: true }],
				interact: {
					target: { group: 'piano-module', midi: 64 },
					playTarget: { group: 'piano-module', anyMidi: true },
					effect: (page) => page.evaluate(() => (window.__audit.scene().getObjectByName('piano-module')?.userData.lastNote?.at ?? 0) + ':' + window.__auditSent.filter((m) => m.op === 'note').length)
				}
			};
		}
	},
	{
		id: 'music-lab',
		async make(page) {
			await menu(page, 'Music Lab: piano + speaker');
			await waitFor(page, () => window.__stores.audioDevices.devicesDebug().built.length >= 2);
			await page.waitForTimeout(800);
			const devices = await devicesOf(page, 'mod-music-lab-');
			const piano = devices.find((d) => d.label === 'piano');
			return {
				items: devices,
				interact: { target: { uuid: piano?.uuid, part: '^key-60$' }, playTarget: { uuid: piano?.uuid, part: '^key-\\d+$' }, effect: sentType('devicenote') }
			};
		}
	},
	{
		id: 'music-dj',
		async make(page) {
			await menu(page, 'Music DJ: booth');
			await waitFor(page, () => window.__stores.audioDevices.devicesDebug().built.length >= 3);
			await page.waitForTimeout(800);
			const devices = await devicesOf(page, 'mod-music-dj-');
			const deck = devices.find((d) => d.label === 'deck');
			return {
				items: devices,
				interact: {
					target: { uuid: deck?.uuid, part: '^dk-play$' },
					effect: (page) => page.evaluate((uuid) => String(window.__stores.audioDevices.devicesDebug().built.find((d) => d.uuid === uuid)?.params?.playing), deck?.uuid)
				}
			};
		}
	},
	{
		id: 'music-voice',
		async make(page) {
			await menu(page, 'Music Voice: demo');
			await waitFor(page, () => window.__stores.audioDevices.devicesDebug().built.length >= 4);
			await page.waitForTimeout(800);
			const devices = await devicesOf(page, 'mod-music-voice-');
			const synth = devices.find((d) => d.label === 'synth');
			return {
				items: devices,
				interact: { target: { uuid: synth?.uuid, part: '^key-\\d+$' }, effect: sentType('devicenote') }
			};
		}
	},
	{
		id: 'music-fx',
		async make(page) {
			await menu(page, 'Music FX: demo chain');
			await waitFor(page, () => window.__stores.audioDevices.devicesDebug().built.length >= 6);
			await page.waitForTimeout(800);
			return { items: await devicesOf(page, 'mod-music-fx-'), ...noClick('no click handler: its knobs are Inspector params and its cables are core\'s patch (mode-free)') };
		}
	},
	{
		id: 'door-keypad',
		async make(page) {
			const door = await create(page, '/create Kpdoor');
			const button = await create(page, '/create Kpbutton1');
			await place(page, button, [-1.2, 1, 0.6]);
			return {
				items: [
					{ label: 'door', uuid: door },
					{ label: 'button', uuid: button }
				],
				interact: { target: { uuid: button }, effect: sentOp('press') }
			};
		}
	},
	{
		id: 'essentials',
		async make(page) {
			await menu(page, 'Spawn essentials demo row');
			await waitFor(page, () => window.__audit.objects().children.filter((c) => c.name.startsWith('Ess')).length >= 6, null, 20000);
			await page.waitForTimeout(800);
			const items = await page.evaluate(() => window.__audit.objects().children.filter((c) => c.name.startsWith('Ess')).map((c) => ({ label: c.name, uuid: c.uuid })));
			const button = items.find((i) => i.label === 'Essbutton');
			return { items, interact: { target: { uuid: button?.uuid }, effect: sentOp('press') } };
		}
	},
	{
		id: 'car',
		async make(page) {
			await menu(page, 'Car: spawn demo car');
			await waitFor(page, () => window.__audit.objects().children.some((c) => c.name === 'Carbody'), null, 20000);
			await page.waitForTimeout(1500);
			const body = await byName(page, 'Carbody');
			const wheel = await page.evaluate(() => window.__audit.objects().children.find((c) => c.name.startsWith('Cylinder'))?.uuid ?? null);
			return {
				items: [
					{ label: 'body', uuid: body },
					{ label: 'wheel', uuid: wheel, from: [1, 0.4, 0.2] }
				],
				interact: { target: { uuid: body }, effect: sentOp('claim') }
			};
		}
	},
	{
		id: 'collectible',
		async make(page) {
			const a = await create(page, '/create box');
			const b = await create(page, '/create box');
			await place(page, a, [-1, 0.5, 0]);
			await place(page, b, [1.5, 0.5, 0]);
			// the module's OWN recipe: select both, its toolbox, Make collectible
			await page.evaluate((ids) => {
				window.__stores.objectActions.selectObject(ids[0]);
				window.__stores.objectActions.selectObject(ids[1], false, true);
			}, [a, b]);
			await page.evaluate(() => window.__stores.moduleToolboxes.openModuleToolbox('mod-collectible-manager'));
			await page.waitForTimeout(900);
			const panel = page.locator('.collectible-manager');
			await panel.locator('.cm-form input[type=text]').fill('gems');
			await panel.locator('.cm-form select').nth(2).selectOption('off').catch(() => {});
			await panel.getByRole('button', { name: 'Make collectible' }).click();
			await page.waitForTimeout(1500);
			await page.evaluate(() => {
				window.__stores.objectActions.deselectObject();
				window.__stores.moduleToolboxes.closeModuleToolbox?.('mod-collectible-manager');
			});
			const nodes = await page.evaluate(() => {
				let g;
				window.__stores.flowGraphs.subscribe((v) => (g = v))();
				return Object.values(g ?? {}).flatMap((graph) => graph.nodes ?? []).filter((n) => n.type === 'collectible').length;
			});
			if (nodes < 1) throw new Error('the recipe built no collectible node');
			return {
				items: [
					{ label: 'gem A', uuid: a },
					{ label: 'gem B', uuid: b }
				],
				interact: { target: { uuid: a } },
				play: { target: { uuid: b } }
			};
		}
	},
	{
		id: 'tutorial-room',
		async make(page) {
			await menu(page, 'Build the tutorial room');
			await waitFor(page, () => !!window.__audit.scene().getObjectByName('tutorial-room'));
			await page.waitForTimeout(500);
			return {
				items: [{ label: 'the room', group: 'tutorial-room', part: '^tutorial-sign-', listLabel: 'Tutorial room', children: true }],
				interact: { target: { group: 'tutorial-room', part: '^tutorial-plinth-select$' }, effect: sentOp('mark') }
			};
		}
	},
	{
		id: 'sabers',
		async make(page) {
			await menu(page, 'Draw / sheathe the saber (K)');
			// the blade needs a pointer to hold: the mouse over the viewport
			await page.mouse.move(VIEW.width / 2, VIEW.height / 2);
			await page.mouse.move(VIEW.width / 2 + 10, VIEW.height / 2 + 5);
			await waitFor(page, () => !!window.__audit.scene().getObjectByName('sabers-module'));
			return {
				items: [{ label: 'the blades', group: 'sabers-module', listLabel: 'Sabers', children: true, noSelect: 'the blade is held AT the pointer — every click would land on it; it is listed and framed from the list instead' }],
				editQuiet: { na: 'no click handler: the blade follows the pointer in every mode' },
				interact: { saber: true },
				play: { saber: true }
			};
		}
	},
	{
		id: '_template',
		moduleId: 'my-module',
		async make(page) {
			const beacon = await create(page, '/create Mybeacon');
			return { items: [{ label: 'beacon', uuid: beacon }], interact: { target: { uuid: beacon }, effect: sentOp('pulse') } };
		}
	},
	{
		id: 'fps-player',
		async make(page) {
			const player = await create(page, '/create Fpsplayer');
			return { items: [{ label: 'player capsule', uuid: player }], ...noClick('no click handler: walking is its J toggle (its own flight)') };
		}
	},
	{
		id: 'avatar',
		async make() {
			return {
				items: [],
				listNa: 'no content of its own: it possesses an object you made',
				...noClick('no click handler: possession is a menu/VR-menu action on the selection (its own card)')
			};
		}
	},
	{
		id: 'flow-toolkit',
		async make() {
			return { items: [], listNa: 'no scene content: flow node definitions only', ...noClick('no scene content: flow node definitions only') };
		}
	},
	// ---- modules whose look belongs to lane 30-visuals-mod (only their registration
	// lines are this lane's): measured through their Games-tab template or toolbox
	{
		id: 'dungeon',
		async make(page) {
			await page.evaluate(() => window.__stores.moduleToolboxes.openModuleToolbox('mod-dungeon-kit'));
			await waitFor(page, () => !!document.getElementById('dk-generate'));
			await page.evaluate(() => document.getElementById('dk-generate').click());
			await waitFor(page, () => (window.__audit.scene().getObjectByName('dungeon-module')?.children.length ?? 0) > 0, null, 20000);
			await page.evaluate(() => window.__stores.moduleToolboxes.closeModuleToolbox?.('mod-dungeon-kit'));
			await page.waitForTimeout(800);
			return {
				items: [{ label: 'the dungeon', group: 'dungeon-module', listLabel: 'Dungeon', children: true, from: [0, 1.6, 0.4] }],
				...noClick('no click handler: the Kit is walked in play through its userData.play contract (dungeon flight)')
			};
		}
	},
	{
		id: 'dungeon-realms',
		zips: ['dungeon', 'dungeon-realms'],
		async make(page) {
			await loadTemplate(page, 'dungeon-realms');
			await waitFor(page, () => !!window.__audit.scene().getObjectByName('dungeon-realms'), null, 20000);
			const plinth = await byName(page, 'Entrance plinth');
			return {
				items: [
					{ label: 'Entrance plinth', uuid: plinth },
					{ label: 'portals + gems', group: 'dungeon-realms', userKey: 'portal', listLabel: 'Dungeon Realms', children: true }
				],
				interact: { target: { group: 'dungeon-realms', userKey: 'portal' } }
			};
		}
	},
	{
		id: 'football',
		async make(page) {
			await loadTemplate(page, 'football');
			const ball = await byName(page, 'Football');
			const lamp = await byName(page, 'Red lamp 1');
			const join = await byName(page, 'Join red');
			return {
				items: [
					{ label: 'ball', uuid: ball },
					{ label: 'a lamp', uuid: lamp },
					{ label: 'Join red', uuid: join }
				],
				interact: { target: { uuid: join } }
			};
		}
	},
	{
		id: 'waves',
		zips: ['health', 'waves'],
		async make(page) {
			await loadTemplate(page, 'waves');
			const enemy = await byName(page, 'Enemy 1');
			const spawn = await byName(page, 'Spawn 1');
			return {
				items: [
					{ label: 'Enemy 1', uuid: enemy },
					{ label: 'Spawn 1', uuid: spawn }
				],
				// a click on an enemy would be HEALTH's (a `click` damage source) — the template
				// wires none: its enemies take KNOCK hits. Health's click is module-health's flight.
				...noClick('waves has no click handler, and the template wires no `click` damage for health (enemies take knock hits)')
			};
		}
	},
	{
		id: 'untangle',
		async make(page) {
			await loadTemplate(page, 'untangle');
			await waitFor(page, () => (window.__audit.scene().getObjectByName('untangle-module')?.children.length ?? 0) > 0, null, 20000);
			return {
				items: [{ label: 'the board', group: 'untangle-module', part: '^untangle-dot-', listLabel: null, children: true }],
				interact: { target: { group: 'untangle-module', part: '^untangle-dot-' } }
			};
		}
	}
];

// ---------------------------------------------------------------------------------
// the checks
// ---------------------------------------------------------------------------------
const cell = (v, note = '') => ({ v, note });

async function setMode(page, mode) {
	await page.evaluate((m) => {
		const s = window.__stores;
		s.isLocked.set(false);
		s.objectActions.deselectObject();
		s.objectActions.setEditorMode(m);
	}, mode);
	// outside the click-cycle window (a repeat on one pixel within 1.5 s walks DOWN)
	await page.waitForTimeout(1700);
}

async function checkList(page, items) {
	await page.evaluate(() => {
		window.__stores.objectListClose.set(false);
		window.__stores.inspectorClose?.set(true);
	});
	await page.waitForTimeout(1200);
	const notes = [];
	let ok = true;
	for (const item of items) {
		if (item.uuid) {
			let found = await page.evaluate((id) => !!document.querySelector('#object-tree')?.querySelector('[id="' + id + '"]'), item.uuid);
			if (!found) {
				// a long tree is virtualised: ask the list's own search for it
				const name = await page.evaluate((id) => window.__audit.objects().getObjectByProperty('uuid', id)?.name ?? '', item.uuid);
				const search = page.locator('#object-search');
				if ((await search.count()) && name) {
					await search.fill(name);
					await page.waitForTimeout(500);
					found = await page.evaluate((id) => !!document.querySelector('#object-tree')?.querySelector('[id="' + id + '"]'), item.uuid);
					await search.fill('');
				}
			}
			if (!found) {
				ok = false;
				notes.push(item.label + ' not in the tree');
			}
		} else {
			const row = page.locator(`#module-content .module-content-row[data-group="${item.group}"]`);
			if ((await row.count()) !== 1) {
				ok = false;
				notes.push(item.group + ': no Module content row');
				continue;
			}
			const label = ((await row.locator('.module-content-name').textContent()) ?? '').trim();
			if (item.listLabel && label !== item.listLabel) {
				ok = false;
				notes.push(`label "${label}" (want "${item.listLabel}")`);
			} else notes.push(`"${label}"`);
			if (item.children) {
				const expander = row.locator('button[aria-label="Show children"]');
				if (await expander.count()) {
					await expander.click();
					await page.waitForTimeout(300);
				}
				const kids = await row.locator('.module-content-child').count();
				if (!kids) {
					ok = false;
					notes.push('no named parts listed');
				} else notes.push(kids + ' parts');
			}
		}
	}
	await page.evaluate(() => window.__stores.objectListClose.set(true));
	await page.waitForTimeout(500);
	return cell(ok ? 'PASS' : 'FAIL', notes.join('; '));
}

/** frame the target and find a clean pixel; a covered one (a HUD card over the middle)
 * retries with the target slid across the view */
async function frameAndAim(page, target, from) {
	let aim = null;
	for (const shift of [[0, 0], [0.45, 0], [-0.45, 0], [0, 0.3], [0.45, 0.3]]) {
		await lib(page, 'frame', target, { from, shift });
		await page.waitForTimeout(700);
		aim = await lib(page, 'aim', target);
		if (aim.ok || !/covered/.test(aim.why ?? '')) return aim;
	}
	return aim;
}

async function clickSelects(page, item) {
	await setMode(page, 'edit');
	const aim = await frameAndAim(page, item, item.from);
	if (!aim.ok) return { ok: false, note: item.label + ': no clean pixel (' + aim.why + ')' };
	await page.mouse.click(aim.x, aim.y);
	await page.waitForTimeout(600);
	if (item.uuid) {
		const sel = await lib(page, 'selection');
		return { ok: sel.includes(item.uuid), note: item.label + (sel.includes(item.uuid) ? '' : ' -> selection ' + JSON.stringify(sel.slice(0, 2)) + ' / proxy ' + (await lib(page, 'moduleSelection'))) };
	}
	const proxy = await lib(page, 'moduleSelection');
	return { ok: proxy === item.group, note: item.label + (proxy === item.group ? ' (proxy)' : ' -> proxy ' + proxy + ', selection ' + JSON.stringify(await lib(page, 'selection'))) };
}

async function checkSelect(page, items) {
	const notes = [];
	let ok = true;
	let any = false;
	for (const item of items) {
		if (item.noSelect) {
			notes.push(item.label + ': N-A — ' + item.noSelect);
			continue;
		}
		any = true;
		const r = await clickSelects(page, item);
		ok = ok && r.ok;
		if (!r.ok || r.note.includes('proxy')) notes.push(r.note);
	}
	if (!any) return cell('N-A', notes.join('; '));
	return cell(ok ? 'PASS' : 'FAIL', notes.join('; '));
}

async function gizmoDrag(page, item) {
	await setMode(page, 'edit');
	await page.evaluate((uuid) => {
		window.__stores.transformMode.set('translate');
		window.__stores.objectActions.selectObject(uuid);
	}, item.uuid);
	await lib(page, 'frame', item, { from: [0.35, 0.8, 1.4], dist: 3.2 });
	await page.waitForTimeout(900);
	const attached = await lib(page, 'gizmoObject');
	if (attached !== item.uuid) return { ok: false, note: item.label + ': no gizmo on it' };
	// the X arrow, else Y or Z (a game's HUD may sit over one of them in the editor)
	let handle = null;
	for (const axis of ['X', 'Z', 'Y']) {
		handle = await lib(page, 'gizmoHandle', axis);
		if (handle?.onCanvas) break;
	}
	if (!handle || !handle.onCanvas) return { ok: false, note: item.label + ': no gizmo handle on the canvas (covered)' };
	const before = await lib(page, 'position', item.uuid);
	await page.mouse.move(handle.x, handle.y);
	await page.waitForTimeout(100);
	await page.mouse.down();
	for (let i = 1; i <= 8; i++) await page.mouse.move(handle.x + handle.dx * i * 10, handle.y + handle.dy * i * 10, { steps: 2 });
	await page.mouse.up();
	await page.waitForTimeout(500);
	const after = await lib(page, 'position', item.uuid);
	const moved = before && after ? Math.hypot(...after.map((v, i) => v - before[i])) : 0;
	return { ok: moved > 0.05, note: item.label + ' moved ' + moved.toFixed(2) + ' m' };
}

async function checkMove(page, items) {
	const notes = [];
	let ok = true;
	let any = false;
	for (const item of items) {
		if (item.uuid) {
			any = true;
			const r = await gizmoDrag(page, item);
			ok = ok && r.ok;
			notes.push(r.note);
		} else {
			if (item.noSelect) {
				notes.push(item.label + ': N-A (not selectable)');
				continue;
			}
			// scene-root content is regenerated by its module: READ-ONLY, through its proxy
			any = true;
			await setMode(page, 'edit');
			const selected = await page.evaluate((g) => {
				window.__stores.objectActions.selectModuleGroup?.(g);
				return window.__stores.moduleSDK.moduleContentDebug().selection?.name ?? null;
			}, item.group);
			// the object list is the documented way: its row click selects the proxy
			let proxy = selected;
			if (proxy !== item.group) {
				await page.evaluate(() => window.__stores.objectListClose.set(false));
				await page.waitForTimeout(900);
				const row = page.locator(`#module-content .module-content-row[data-group="${item.group}"] .module-content-name`);
				if (await row.count()) await row.click();
				await page.waitForTimeout(600);
				proxy = await lib(page, 'moduleSelection');
				await page.evaluate(() => window.__stores.objectListClose.set(true));
			}
			const gizmo = await lib(page, 'gizmoObject');
			const sel = await lib(page, 'selection');
			const inObjects = await page.evaluate((g) => !!window.__audit.objects().getObjectByName(g), item.group);
			const readOnly = proxy === item.group && !gizmo && sel.length === 0 && !inObjects;
			ok = ok && readOnly;
			notes.push(item.label + (readOnly ? ': read-only (proxy, no gizmo)' : `: proxy ${proxy}, gizmo ${gizmo}, selection ${sel.length}, in objectsGroup ${inObjects}`));
		}
	}
	if (!any) return cell('N-A', notes.join('; '));
	return cell(ok ? 'PASS' : 'FAIL', notes.join('; '));
}

/** read an effect; the default is the generic reaction */
async function effectOf(page, spec) {
	if (spec.effect) return spec.effect(page);
	return lib(page, 'reaction');
}
const changed = (a, b) => JSON.stringify(a) !== JSON.stringify(b);

async function clickEffect(page, mode, spec) {
	await setMode(page, mode);
	const aim = await frameAndAim(page, spec.target, spec.target.from);
	if (!aim.ok) return { ok: null, note: 'no clean pixel (' + aim.why + ')' };
	await page.evaluate(() => window.__stores.toastStore.set([]));
	const mark = await page.evaluate(() => window.__auditSent.length);
	const before = await effectOf(page, spec);
	await page.mouse.click(aim.x, aim.y);
	await page.waitForTimeout(900);
	const after = await effectOf(page, spec);
	const types = await page.evaluate((m) => window.__auditSent.slice(m).map((x) => x.type + (x.op ? ':' + x.op : '')).join(','), mark);
	const sel = await lib(page, 'selection');
	const proxy = await lib(page, 'moduleSelection');
	return { ok: changed(before, after), selected: sel.length > 0 || !!proxy, note: JSON.stringify(before) + ' -> ' + JSON.stringify(after) + ` (hit ${aim.first}; sent ${types || 'nothing'})` };
}

async function checkEditQuiet(page, spec) {
	if (spec.editQuiet?.na) return cell('N-A', spec.editQuiet.na);
	if (!spec.interact?.target) return cell('N-A', spec.interact?.na ?? 'no interactive part');
	const r = await clickEffect(page, 'edit', spec.interact);
	if (r.ok === null) return cell('FAIL', r.note);
	const quiet = !r.ok && r.selected;
	return cell(quiet ? 'PASS' : 'FAIL', (r.ok ? 'INTERACTED in Edit: ' : '') + (r.selected ? '' : 'selected nothing; ') + r.note);
}

async function checkInteract(page, spec) {
	const i = spec.interact;
	if (!i || i.na) return cell('N-A', i?.na ?? 'no interactive part');
	if (i.saber) return saberCheck(page, 'interact');
	const r = await clickEffect(page, 'interact', i);
	if (r.ok === null) return cell('FAIL', r.note);
	const ok = r.ok && !r.selected;
	return cell(ok ? 'PASS' : 'FAIL', (r.selected ? 'ALSO SELECTED; ' : '') + r.note);
}

async function tap(page) {
	await page.evaluate(
		() =>
			new Promise((resolve) => {
				window.dispatchEvent(new PointerEvent('pointerdown', { button: 0, bubbles: true }));
				setTimeout(() => {
					window.dispatchEvent(new PointerEvent('pointerup', { button: 0, bubbles: true }));
					resolve(true);
				}, 120);
			})
	);
}

async function checkPlay(page, spec) {
	const p = spec.play ?? spec.interact;
	if (!p || p.na) return cell('N-A', p?.na ?? 'no interactive part');
	if (p.saber) return saberCheck(page, 'play');
	await setMode(page, 'edit');
	await page.evaluate(() => window.__stores.isLocked.set(true));
	await page.waitForTimeout(800);
	// a game whose Start screen is up in play holds the pointer for its menu (21-E3's
	// substate) — press Start the way its button does: the game state goes to playing
	const started = await page.evaluate(() => {
		let free;
		window.__stores.playPointerFree.subscribe((v) => (free = v))();
		if (free) window.__stores.gameState.setGameState('playing');
		return free;
	});
	if (started) await page.waitForTimeout(800);
	const target = p.playTarget ?? p.target;
	await lib(page, 'aimRig', target, 1.6);
	await page.waitForTimeout(500);
	let aim = await lib(page, 'centreAim', target);
	if (!aim.ok) {
		await lib(page, 'placeCentre', target, 1.6);
		await page.waitForTimeout(500);
		aim = await lib(page, 'centreAim', target);
	}
	if (!aim.ok) {
		await page.evaluate(() => window.__stores.isLocked.set(false));
		return cell('FAIL', 'the crosshair is not on it (' + aim.first + ' @ ' + aim.distance + ')');
	}
	await page.evaluate(() => window.__stores.toastStore.set([]));
	const before = await effectOf(page, p);
	await tap(page);
	await page.waitForTimeout(900);
	const after = await effectOf(page, p);
	const debug = await lib(page, 'playDebug');
	await page.evaluate(() => window.__stores.isLocked.set(false));
	await page.waitForTimeout(400);
	return cell(changed(before, after) ? 'PASS' : 'FAIL', JSON.stringify(before) + ' -> ' + JSON.stringify(after) + ' (crosshair on ' + aim.first + (started ? '; Start pressed' : '') + '; play ' + JSON.stringify(debug) + ')');
}

/** Sabers: the blade must reach an object under the pointer (Interact: the mouse ray;
 * Play: the crosshair ray, 30 P4) and spark a hit */
async function saberCheck(page, mode) {
	await setMode(page, 'edit');
	if (mode === 'interact') await page.evaluate(() => window.__stores.objectActions.setEditorMode('interact'));
	if (mode === 'play') {
		await page.evaluate(() => window.__stores.isLocked.set(true));
		await page.waitForTimeout(800);
	}
	const box = await create(page, '/create box');
	// one metre down the ray through the view's centre: inside the blade (0.55 .. 1.75 m)
	await page.evaluate((uuid) => {
		const s = window.__stores;
		let camera;
		s.globalCamera.subscribe((v) => (camera = v))();
		const at = camera.getWorldPosition(new s.THREE.Vector3()).addScaledVector(camera.getWorldDirection(new s.THREE.Vector3()), 1.1);
		let g;
		s.objectsGroup.subscribe((v) => (g = v))();
		const o = g.getObjectByProperty('uuid', uuid);
		o.position.copy(at);
		o.scale.setScalar(0.5);
		o.updateMatrixWorld(true);
		s.objectsGroup.update((v) => v);
	}, box);
	const before = await sentOp('hit')(page);
	for (let i = 0; i < 6; i++) {
		await page.mouse.move(VIEW.width / 2 + (i % 2), VIEW.height / 2 + (i % 3));
		await page.waitForTimeout(150);
	}
	await page.waitForTimeout(600);
	const after = await sentOp('hit')(page);
	if (mode === 'play') await page.evaluate(() => window.__stores.isLocked.set(false));
	await page.evaluate((uuid) => window.__stores.commandsHandler.sceneCommand('/clear ' + uuid), box);
	return cell(after > before ? 'PASS' : 'FAIL', 'hit sparks ' + before + ' -> ' + after);
}

// ---------------------------------------------------------------------------------
async function auditModule(browser, spec) {
	const row = {};
	const peer = await h.setupPage(browser, spec.id, { context: { viewport: VIEW } });
	const page = peer.page;
	const errors = [];
	page.on('pageerror', (e) => errors.push(String(e.message).slice(0, 120)));
	try {
		for (const zip of spec.zips ?? [spec.id]) await h.installModule(peer, zip, zip === spec.id ? spec.moduleId ?? zip : zip);
		await installLib(page);
		await page.evaluate(() => {
			window.__stores.objectListClose.set(true);
			window.__stores.inspectorClose?.set(true);
		});
		const made = await spec.make(page);
		made.items = (made.items ?? []).filter((i) => i.uuid || i.group);
		row.list = made.listNa ? cell('N-A', made.listNa) : await checkList(page, made.items);
		row.select = made.items.length ? await checkSelect(page, made.items) : cell('N-A', made.listNa ?? 'no content');
		row.move = made.items.length ? await checkMove(page, made.items) : cell('N-A', made.listNa ?? 'no content');
		row.editQuiet = await checkEditQuiet(page, made);
		row.interact = await checkInteract(page, made);
		row.play = await checkPlay(page, made);
	} catch (error) {
		for (const c of COLUMNS) row[c] ??= cell('FAIL', 'flight error: ' + String(error.message).slice(0, 160));
	}
	row.errors = errors;
	await peer.ctx.close();
	return row;
}

h.run(async () => {
	const browser = await h.launch({ args: h.GPU_ARGS });
	const renderer = await (async () => {
		const probe = await h.setupPage(browser, 'gpu');
		const r = await probe.page.evaluate(() => {
			const gl = document.createElement('canvas').getContext('webgl2');
			const ext = gl?.getExtension('WEBGL_debug_renderer_info');
			return ext ? gl.getParameter(ext.UNMASKED_RENDERER_WEBGL) : 'unknown';
		});
		await probe.ctx.close();
		return r;
	})();
	console.log('renderer: ' + renderer);
	const table = {};
	for (const spec of MODULES) {
		if (ONLY.length && !ONLY.includes(spec.id)) continue;
		console.log('\n=== ' + spec.id + ' ===');
		const row = await auditModule(browser, spec);
		table[spec.id] = row;
		for (const c of COLUMNS) {
			const { v, note } = row[c];
			if (v === 'N-A') console.log('N-A  ' + spec.id + ' ' + c + ' — ' + note);
			else h.check(v === 'PASS', spec.id + ' ' + c + (note ? ' — ' + note : ''));
		}
		h.check(row.errors.length === 0, spec.id + ': the page threw nothing' + (row.errors.length ? ' (' + row.errors.join(' / ') + ')' : ''));
	}
	console.log('\n| module | ' + COLUMNS.join(' | ') + ' |');
	console.log('|---|' + COLUMNS.map(() => '---').join('|') + '|');
	for (const [id, row] of Object.entries(table)) console.log('| ' + id + ' | ' + COLUMNS.map((c) => row[c].v).join(' | ') + ' |');
	if (process.env.AUDIT_OUT) fs.writeFileSync(process.env.AUDIT_OUT, JSON.stringify({ renderer, app: h.URL, table }, null, 2));
	await h.finish(browser);
});
