// build the GLB loader an OLD core needs for the Waves models (run by `npm run build:waves`,
// before the module bundle). 34 R7: a core with api.loadModel never fetches it. The api hands a module THREE only — no GLTFLoader (DEVX #36) — and bundling
// three's loader the normal way would drag a SECOND three into the module, whose classes are
// not the scene's. So three's own GLTFLoader + SkeletonUtils are bundled against a SHIM that
// re-exports the RUNTIME three (`globalThis.__wavesTHREE`, set by src/assets.js right before
// it imports the chunk from a blob). The shim lists exactly the names those files import.
// Output: assets/gltf-loader.js — a PACKAGED file (manifest `files`), committed like module.js,
// fetched by src/assets.js only when the core has no api.loadModel (it used to be embedded in
// module.js as text: 45 KB every install parsed and only old cores used).
import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const jsm = join(dirname(dirname(require.resolve('three'))), 'examples/jsm'); // …/three/build/three.cjs → …/three
const files = ['loaders/GLTFLoader.js', 'utils/SkeletonUtils.js', 'utils/BufferGeometryUtils.js'].map((f) => join(jsm, f));

/** @type {Set<string>} */
const names = new Set();
for (const f of files)
	for (const m of readFileSync(f, 'utf8').matchAll(/import\s*\{([^}]*)\}\s*from\s*['"]three['"]/g))
		for (const n of m[1].split(',')) if (n.trim()) names.add(n.trim().split(/\s+as\s+/)[0]);
const shim =
	'// GENERATED by build-gltf.mjs — the runtime three, re-exported for the loader chunk\n' +
	'const T = globalThis.__wavesTHREE;\n' +
	'if (!T) throw new Error("waves: __wavesTHREE unset before the loader chunk");\n' +
	[...names].sort().map((n) => `export const ${n} = T.${n};`).join('\n') +
	'\n';
// src/gltf holds only generated (gitignored) files, so a fresh clone has no such folder
mkdirSync(join(here, 'src/gltf'), { recursive: true });
const shimFile = join(here, 'src/gltf/three-shim.gen.js');
writeFileSync(shimFile, shim);

const out = await build({
	stdin: {
		contents: `export { GLTFLoader } from ${JSON.stringify(files[0])};\nexport { clone as cloneSkinned } from ${JSON.stringify(files[1])};\n`,
		resolveDir: here,
		loader: 'js'
	},
	bundle: true,
	format: 'esm',
	minify: true,
	write: false,
	// exactly the bare 'three' goes to the shim (an alias would also remap three/addons/…)
	plugins: [{ name: 'three-shim', setup: (b) => b.onResolve({ filter: /^three$/ }, () => ({ path: shimFile })) }],
	legalComments: 'none'
});
const code = out.outputFiles[0].text;
mkdirSync(join(here, 'assets'), { recursive: true });
writeFileSync(join(here, 'assets/gltf-loader.js'), code);
console.log(`assets/gltf-loader.js written: ${code.length} bytes, ${names.size} three names shimmed`);
