// Bake the props-kit WallTorch (packs `props-kit/WallTorch`, CC0, made with Meshy.ai +
// procedural) into a small generated JS module the Kit draws as INSTANCED meshes
// (run by `npm run build:dungeon`, before the bundle).
//
// Why not a GLTF loader: the api hands a module THREE and no loader (DEVX #36), and the
// Kit draws every torch of a floor as ONE InstancedMesh per part — so what it needs is the
// raw geometry + the three material maps, which a GLB already holds in plain arrays.
// Output: src/torch/torch.gen.js (gitignored): per node {name, translation, positions,
// normals, uvs, index} as base64 typed arrays + {roughness, metalness, color, emissive,
// emissiveStrength, map (a JPEG data URL)} and the node's bounds.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const glb = readFileSync(join(here, 'assets/wall-torch.glb'));
if (glb.readUInt32LE(0) !== 0x46546c67) throw new Error('wall-torch.glb: not a GLB');
const jsonLen = glb.readUInt32LE(12);
const gltf = JSON.parse(glb.subarray(20, 20 + jsonLen).toString('utf8'));
const binStart = 20 + jsonLen + 8;
const bin = glb.subarray(binStart, binStart + glb.readUInt32LE(20 + jsonLen));

/** @param {number} i */
function viewBytes(i) {
	const v = gltf.bufferViews[i];
	return bin.subarray(v.byteOffset ?? 0, (v.byteOffset ?? 0) + v.byteLength);
}
const SIZE = { SCALAR: 1, VEC2: 2, VEC3: 3, VEC4: 4 };
/** an accessor as a tightly packed typed array, base64 @param {number} i */
function accessor(i) {
	const a = gltf.accessors[i];
	const n = a.count * SIZE[a.type];
	const T = a.componentType === 5126 ? Float32Array : a.componentType === 5125 ? Uint32Array : a.componentType === 5123 ? Uint16Array : null;
	if (!T) throw new Error('unsupported component type ' + a.componentType);
	const src = viewBytes(a.bufferView);
	const stride = gltf.bufferViews[a.bufferView].byteStride;
	const out = new T(n);
	const dv = new DataView(src.buffer, src.byteOffset + (a.byteOffset ?? 0));
	const comp = T.BYTES_PER_ELEMENT;
	const per = SIZE[a.type];
	for (let e = 0; e < a.count; e++)
		for (let c = 0; c < per; c++) {
			const off = e * (stride ?? per * comp) + c * comp;
			out[e * per + c] = T === Float32Array ? dv.getFloat32(off, true) : T === Uint32Array ? dv.getUint32(off, true) : dv.getUint16(off, true);
		}
	// indices fit 16 bits here (394 verts): half the bytes
	const packed = T === Uint32Array ? Uint16Array.from(out) : out;
	return { b64: Buffer.from(packed.buffer, packed.byteOffset, packed.byteLength).toString('base64'), type: packed.constructor.name, min: a.min, max: a.max };
}
/** @param {number} i */
function imageUrl(i) {
	const img = gltf.images[gltf.textures[i].source];
	return 'data:' + img.mimeType + ';base64,' + Buffer.from(viewBytes(img.bufferView)).toString('base64');
}

const parts = gltf.nodes.map((node) => {
	const prim = gltf.meshes[node.mesh].primitives[0];
	const mat = gltf.materials[prim.material];
	const pbr = mat.pbrMetallicRoughness ?? {};
	const pos = accessor(prim.attributes.POSITION);
	return {
		name: node.name,
		translation: node.translation ?? [0, 0, 0],
		positions: pos.b64,
		normals: accessor(prim.attributes.NORMAL).b64,
		uvs: prim.attributes.TEXCOORD_0 != null ? accessor(prim.attributes.TEXCOORD_0).b64 : null,
		index: accessor(prim.indices).b64,
		min: pos.min,
		max: pos.max,
		material: {
			roughness: pbr.roughnessFactor ?? 1,
			metalness: pbr.metallicFactor ?? 1,
			color: pbr.baseColorFactor ?? [1, 1, 1, 1],
			emissive: mat.emissiveFactor ?? null,
			emissiveStrength: mat.extensions?.KHR_materials_emissive_strength?.emissiveStrength ?? 1,
			map: pbr.baseColorTexture ? imageUrl(pbr.baseColorTexture.index) : null
		}
	};
});

mkdirSync(join(here, 'src/torch'), { recursive: true });
writeFileSync(
	join(here, 'src/torch/torch.gen.js'),
	'// GENERATED by build-torch.mjs from assets/wall-torch.glb (props-kit WallTorch, CC0) — do not edit\n' +
		'export const TORCH_PARTS = ' + JSON.stringify(parts) + ';\n'
);
console.log('torch: ' + parts.map((p) => p.name).join(', '));
